source('ReadSubsetData.R')
subsetdata$Global_active_power <- as.numeric(as.character(subsetdata$Global_active_power))
subsetdata$Global_reactive_power <- as.numeric(as.character(subsetdata$Global_reactive_power))
subsetdata$Voltage <- as.numeric(as.character(subsetdata$Voltage))
subsetdata$Global_intensity <- as.numeric(as.character(subsetdata$Global_intensity))
subsetdata$dt <- paste(subsetdata$Date, subsetdata$Time)
subsetdata$dt <- strptime(subsetdata$dt, "%d/%m/%Y %H:%M:%S")
png(file = "plot2.png",width = 480, height = 480)
plot(subsetdata$dt,subsetdata$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()